mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "ground_truth",
    ]

    initial_state_estimator: "ground_truth" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:

    midair_activation:

      rate: 100 # [Hz]

      during_activation:
        controller: "MidairActivationController"
        tracker: "MidairActivationTracker"

      after_activation:
        controller: "Se3Controller"
        tracker: "MpcTracker"

    min_height_checking:
      enabled: false

    max_height_checking:
      enabled: false
