hw_interface_plugin: "mrs_uav_coppelia_api/Api"

gnss:
  utm_zone: "32T"
  utm_x: 465710.758973
  utm_y: 5249465.43086
  amsl: 340.0

input_mode:
  actuators:             false
  control_group:         false
  attitude_rate:         true
  attitude:              false
  acceleration_hdg_rate: false
  velocity_hdg_rate:     false

outputs:
  distance_sensor: false
  gnss: true
  imu: true
  altitude: true
  magnetometer_heading: true
  rc_channels: false
  battery_state: true
  position: false
  orientation: false
  velocity: false
  angular_velocity: false
  odometry: true

topics:
  prefix: "coppelia_simulator"
  simulator:
    # subscribers
    imu: "imu"
    odom: "odometry"
    rangefinder: "rangefinder"
    # publishers
    actuators_cmd: "actuators_cmd"
    control_group_cmd: "control_group_cmd"
    attitude_rate_cmd: "attitude_rate_cmd"
    attitude_cmd: "attitude_cmd"
    acceleration_hdg_rate_cmd: "acceleration_hdg_rate_cmd"
    velocity_hdg_rate_cmd: "velocity_hdg_rate_cmd"
